### PR TITLE
Fix: Adding evidence using the SDK

### LINKED ISSUE #76: [SDK] Evidence Creation
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

SDK

### To Reproduce

1. create an evidence using the sdk:
- `await repo.hypercerts.addEvidence(hypercertURI,evidencePayload)` 

### Describe the Bug

1. Unlike `repo.hypercerts.create` which only expects the actual payload:
```
export interface CreateHypercertParams {
  title: string;
  description: string;
  workScope?: {
    withinAllOf?: string[];
    withinAnyOf?: string[];
    withinNoneOf?: string[];
  };
  startDate: string;
  endDate: string;
  rights: {
    name: string;
    type: string;
    description: string;
  };
  shortDescription: string;
  image?: Blob;
  location?: {
    value: string;
    name?: string;
    description?: string;
    srs: string;
    geojson?: Blob;
  };
  contributions?: Array<{
    contributors: string[];
    role: string;
    description?: string;
  }>;
  evidence?: HypercertEvidence[];
  onProgress?: (step: ProgressStep) => void;
}
```
`repo.hypercerts.addEvidence` requires the whole record addition structure along with the `$type`

see `packages/sdk-core/src/repository/HypercertOperationsImpl.ts` `line 884`
`async addEvidence(hypercertUri: string, evidence: HypercertEvidence[])`

where `HypercertEvidence` is the `Main` of  `org.hypercerts.claim.evidence`.

2. It also saves the evidence inside of the activity `org.hypercerts.claim.activity` instead of creating its own record

### Expected Behavior

1. We only send the payload to the sdk and the sdk should handle the boilerplate of adding the `NSID`
2. The evidence should be its own record instead of being saved inside of the activity record
3. It should add the hypercert as a subject, or there should be a parameter to provide the `subject` which is defined in `org.hypercerts.claim.evidence` lexicon

### PR DESCRIPTION
**Pull request by Kzoeps**
Currently evidence gets saved inside of the hypercert. However according to our lexicons we have to store it as a record which links to the hypercert through the subject uri.

Also the sdk currently expects the whole body from whoever is using it, with `$type` and also creating the subject uri. Which isnt the most developer friendly. So mimicking hypercert.create, sdk `addEvidence` now handles the record creation, blob  upload and linking with the hypercert URI.

Fixes #76 

## Summary by CodeRabbit

* **Breaking Changes**
  * addEvidence now takes a single evidence input object and evidence is no longer embedded in hypercerts — access via result.evidenceUris.

* **New Features**
  * Evidence created as separate records (URI or uploaded blob).
  * create() adds evidence in parallel and exposes evidenceUris.
  * Added progress-tracked evidence creation (createEvidenceWithProgress).

* **Tests**
  * Added tests for URI/blob evidence creation and evidence-added events.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts [hunk 1]
```diff
@@ -856,38 +857,64 @@ export class HypercertOperationsImpl extends EventEmitter<HypercertEvents> imple
...
-   * Evidence is appended to existing evidence, not replaced.
-   *
-   * @example
-   * ```typescript
-   * await repo.hypercerts.addEvidence(hypercertUri, [
-   *   { uri: "https://example.com/report.pdf", description: "Impact report" },
-   *   { uri: "https://example.com/data.csv", description: "Raw data" },
-   * ]);
-   * ```
    */
```
Comment (aspiers) [inline packages/sdk-core/src/repository/HypercertOperationsImpl.ts:877]: Would be nice to keep an example. At some point we will want to auto-generate API reference docs for the SDK, and then these docstrings will matter more.

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts [hunk 2]
```diff
@@ -856,38 +857,64 @@ export class HypercertOperationsImpl extends EventEmitter<HypercertEvents> imple
...
 
-      const result = await this.update({
-        uri: hypercertUri,
-        updates: { evidence: updatedEvidence },
-      });
+      let evidenceContent: HypercertEvidence["content"];
+      if (typeof content === "string") {
+        evidenceContent = {
+          $type: "org.hypercerts.defs#uri",
+          uri: content,
```
Comment (aspiers) [inline packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: What if the content is an inline string rather than a URI? That is allowed according to [this comment below](https://github.com/hypercerts-org/hypercerts-sdk/pull/84/changes#diff-a7e4fb7f9bf19c04d837168b7493f9fae0c669bebcc7888c686b259c876fe259R280).

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts [hunk 3]
```diff
@@ -856,38 +857,64 @@ export class HypercertOperationsImpl extends EventEmitter<HypercertEvents> imple
...
-   *
-   * @example
-   * ```typescript
-   * await repo.hypercerts.addEvidence(hypercertUri, [
-   *   { uri: "https://example.com/report.pdf", description: "Impact report" },
-   *   { uri: "https://example.com/data.csv", description: "Raw data" },
-   * ]);
-   * ```
    */
-  async addEvidence(hypercertUri: string, evidence: HypercertEvidence[]): Promise<UpdateResult> {
```
Comment (aspiers) [inline packages/sdk-core/src/repository/HypercertOperationsImpl.ts:878]: So we're changing from allowing adding multiple evidence records in one go, to having to call the function once for each record?  That sounds absolutely fine to me but I think it needs clarifying a bit in the changeset, as it's a breaking change.

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts [hunk 4]
```diff
@@ -856,38 +857,64 @@ export class HypercertOperationsImpl extends EventEmitter<HypercertEvents> imple
...
-        updates: { evidence: updatedEvidence },
-      });
+      let evidenceContent: HypercertEvidence["content"];
+      if (typeof content === "string") {
+        evidenceContent = {
+          $type: "org.hypercerts.defs#uri",
+          uri: content,
+        };
+      } else {
+        // Handle Blob upload
```
Comment (aspiers) [inline packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: I find that often when there's a short one-line comment like this, it's a sign of an opportunity for a simple extract function refactoring.

In this case, this `else` clause can be refactored into a separate function (e.g. `handleBlobUpload()`).  This is a good example of a general coding principle: ideally functions should do just one thing well, rather than being longer and doing multiple things.  It makes the code easier to read and maintain.  It can sometimes also make it easier to test, although in this case maybe mocking a `handleBlobUpload()` method isn't necessarily better than mocking the `com.atproto.repo.uploadBlob` call directly, since you still need a `mockAgent` either way.

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts [hunk 5]
```diff
@@ -856,38 +857,64 @@ export class HypercertOperationsImpl extends EventEmitter<HypercertEvents> imple
...
-      const updatedEvidence = [...existingEvidence, ...evidence];
+      const { subjectUri, content, ...rest } = evidence;
+      const subject = await this.get(subjectUri);
+      const createdAt = new Date().toISOString();
 
-      const result = await this.update({
-        uri: hypercertUri,
-        updates: { evidence: updatedEvidence },
-      });
+      let evidenceContent: HypercertEvidence["content"];
```
Comment (aspiers) [inline packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: Similarly to my comment below about small functions doing one thing, this could be

```suggestion
      const evidenceContent = this.getHypercertEvidence(content);
```

**Review by aspiers — COMMENTED** [review]
Looks mostly great, would prefer some simple refactorings to avoid a long function, and for the changeset to clarify the breaking change.

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts (hunk 3 above)
Comment (Kzoeps) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts:878]: added!

File: .changeset/fix-add-evidence.md [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+- Remove inline evidence embedding from hypercert records
+- Add `evidenceUris?: string[]` to `CreateHypercertResult` interface
+- Add `createEvidenceWithProgress()` helper method with "addEvidence" progress tracking
+- `addEvidence()` SDK constructs `$type`, `createdAt`, and `subject` fields internally
+
+**Breaking Changes:**
+
+- Evidence is no longer embedded in the hypercert record - use `result.evidenceUris` to access evidence record URIs
+- `addEvidence()` now accepts a single `CreateHypercertEvidenceParams` object instead of
+  `(uri: string, evidence: HypercertEvidence[])`
```
[the remark this answers is not in the document]
Comment (Kzoeps) [reply .changeset/fix-add-evidence.md:17]: @aspiers should this be a major bump or is it fine to leave it as a minor

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts (hunk 4 above)
Comment (Kzoeps) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: done!

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts (hunk 1 above)
Comment (Kzoeps) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts:877]: added!

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts (hunk 2 above)
Comment (Kzoeps) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: i've updated the docs for it. the format should either be a uri or a string according to our lexicons. Let me know if thats the way we should go about it or if we should add a validation inside of the sdk

**Comment by Kzoeps** [comment]
📎 **Related PR:** #96 builds on top of this PR and adds a generic `resolveUriOrBlob` helper that refactors both evidence and location operations. PR #96 should be merged after this one to avoid conflicts.

File: .changeset/fix-add-evidence.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (aspiers) [reply .changeset/fix-add-evidence.md:17]: `minor` is correct.

@coderabbitai is confusing `@hypercerts-org/sdk-core` with `@hypercerts-org/sdk`.  The latter does indeed have version 2.9.0, but that's the old Hypercerts v0.1 SDK which we're not touching.  The current published version of `@hypercerts-org/sdk-core` is 0.10.0-beta.4 as seen at https://www.npmjs.com/package/@hypercerts-org/sdk-core or via `npm view`.  @coderabbitai you should learn from this mistake for the future.

The `@hypercerts-org/sdk-react` package is also part of the new Hypercerts v0.2 generation, similarly to `@hypercerts-org/sdk-core`.

File: packages/sdk-core/src/repository/HypercertOperationsImpl.ts (hunk 2 above)
Comment (aspiers) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: Yes I think the SDK is the right place for validation of business logic like this, and it's necessary because we can't really enforce it anywhere else, except for perhaps external validation services which monitor for integrity violations after they've already been posted to the PDS/SDS - but those are already too late.  The SDK is the only place we can consistently catch it up front.

Comment (aspiers) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: That said, we can deal with this in a follow-up.

Comment (aspiers) [reply packages/sdk-core/src/repository/HypercertOperationsImpl.ts]: Filed as #97.

**Review by aspiers — APPROVED** [review]
Awesome!
